export const CHAIN_LIST = {
    "ETH": {
        "chain_id": process.env.ETH_CHAIN_ID,
        "rpc": process.env.ETH_RPC_ENDPOINTS,
        "transfer_gas": process.env.ETH_TX_GAS,
        "min_gas": process.env.ETH_MIN_GAS_PRICE,
        "max_gas": process.env.ETH_MAX_GAS_PRICE,
        "block_time": process.env.ETH_BLOCK_GENERATION_TIME,
        "gas_coefficient": process.env.ETH_GAS_PRICE_COEFFICIENT,
        "gas_price_update_period": process.env.ETH_GAS_PRICE_UPDATE_PERIOD,
        "native_symbol": "ETH",
    },
    "BSC": {
        "chain_id": process.env.BSC_CHAIN_ID,
        "rpc": process.env.BSC_RPC_ENDPOINTS,
        "transfer_gas": process.env.BSC_TX_GAS,
        "min_gas": process.env.BSC_MIN_GAS_PRICE,
        "max_gas": process.env.BSC_MAX_GAS_PRICE,
        "block_time": process.env.BSC_BLOCK_GENERATION_TIME,
        "gas_coefficient": process.env.BSC_GAS_PRICE_COEFFICIENT,
        "gas_price_update_period": process.env.BSC_GAS_PRICE_UPDATE_PERIOD,
        "native_symbol": "BNB",
    },
    "POLYGON": {
        "chain_id": process.env.POLYGON_CHAIN_ID,
        "rpc": process.env.POLYGON_RPC_ENDPOINTS,
        "transfer_gas": process.env.POLYGON_TX_GAS,
        "min_gas": process.env.POLYGON_MIN_GAS_PRICE,
        "max_gas": process.env.POLYGON_MAX_GAS_PRICE,
        "block_time": process.env.POLYGON_BLOCK_GENERATION_TIME,
        "gas_coefficient": process.env.POLYGON_GAS_PRICE_COEFFICIENT,
        "gas_price_update_period": process.env.POLYGON_GAS_PRICE_UPDATE_PERIOD,
        "native_symbol": "MATIC",
    },
    "AVALANCHE": {
        "chain_id": process.env.AVALANCHE_CHAIN_ID,
        "rpc": process.env.AVALANCHE_RPC_ENDPOINTS,
        "transfer_gas": process.env.AVALANCHE_TX_GAS,
        "min_gas": process.env.AVALANCHE_MIN_GAS_PRICE,
        "max_gas": process.env.AVALANCHE_MAX_GAS_PRICE,
        "block_time": process.env.AVALANCHE_BLOCK_GENERATION_TIME,
        "gas_coefficient": process.env.AVALANCHE_GAS_PRICE_COEFFICIENT,
        "gas_price_update_period": process.env.AVALANCHE_GAS_PRICE_UPDATE_PERIOD,
        "native_symbol": "AVAX",
    },
}